
/*
  Copyright (c) 2010, Nicolas Garcia Belmonte
  All rights reserved

  > Redistribution and use in source and binary forms, with or without
  > modification, are permitted provided that the following conditions are met:
  >      * Redistributions of source code must retain the above copyright
  >        notice, this list of conditions and the following disclaimer.
  >      * Redistributions in binary form must reproduce the above copyright
  >        notice, this list of conditions and the following disclaimer in the
  >        documentation and/or other materials provided with the distribution.
  >      * Neither the name of the organization nor the
  >        names of its contributors may be used to endorse or promote products
  >        derived from this software without specific prior written permission.
  >
  >  THIS SOFTWARE IS PROVIDED BY NICOLAS GARCIA BELMONTE ``AS IS'' AND ANY
  >  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  >  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  >  DISCLAIMED. IN NO EVENT SHALL NICOLAS GARCIA BELMONTE BE LIABLE FOR ANY
  >  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  >  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  >  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  >  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  >  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  >  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
 (function(){window.$jit=function(a){a=a||window;for(var b in $jit)$jit[b].$extend&&(a[b]=$jit[b])};$jit.version="2.0.0b";var e=function(a){return document.getElementById(a)};e.empty=function(){};e.extend=function(a,b){for(var c in b||{})a[c]=b[c];return a};e.lambda=function(a){return typeof a=="function"?a:function(){return a}};e.time=Date.now||function(){return+new Date};e.splat=function(a){var b=e.type(a);return b?b!="array"?[a]:a:[]};e.type=function(a){var b=e.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
if(b!="object")return b;if(a&&a.$$family)return a.$$family;return a&&a.nodeName&&a.nodeType==1?"element":b};e.type.s=Object.prototype.toString;e.each=function(a,b){if(e.type(a)=="object")for(var c in a)b(a[c],c);else{c=0;for(var d=a.length;c<d;c++)b(a[c],c)}};e.indexOf=function(a,b){if(Array.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};e.map=function(a,b){var c=[];e.each(a,function(a,f){c.push(b(a,f))});return c};e.reduce=function(a,b,c){var d=a.length;
if(d==0)return c;for(var f=arguments.length==3?c:a[--d];d--;)f=b(f,a[d]);return f};e.merge=function(){for(var a={},b=0,c=arguments.length;b<c;b++){var d=arguments[b];if(e.type(d)=="object")for(var f in d){var h=d[f],g=a[f];a[f]=g&&e.type(h)=="object"&&e.type(g)=="object"?e.merge(g,h):e.unlink(h)}}return a};e.unlink=function(a){var b;switch(e.type(a)){case "object":b={};for(var c in a)b[c]=e.unlink(a[c]);break;case "array":b=[];c=0;for(var d=a.length;c<d;c++)b[c]=e.unlink(a[c]);break;default:return a}return b};
e.zip=function(){if(arguments.length===0)return[];for(var a=0,b=[],c=arguments.length,d=arguments[0].length;a<d;a++){for(var f=0,h=[];f<c;f++)h.push(arguments[f][a]);b.push(h)}return b};e.rgbToHex=function(a,b){if(a.length<3)return null;if(a.length==4&&a[3]==0&&!b)return"transparent";for(var c=[],d=0;d<3;d++){var f=(a[d]-0).toString(16);c.push(f.length==1?"0"+f:f)}return b?c:"#"+c.join("")};e.hexToRgb=function(a){if(a.length!=7){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(a.length!=
3)return null;for(var b=[],c=0;c<3;c++){var d=a[c];d.length==1&&(d+=d);b.push(parseInt(d,16))}return b}else return a=parseInt(a.slice(1),16),[a>>16,a>>8&255,a&255]};e.destroy=function(a){e.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};e.clean=function(a){a=a.childNodes;for(var b=0,c=a.length;b<c;b++)e.destroy(a[b])};e.addEvent=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};e.addEvents=function(a,b){for(var c in b)e.addEvent(a,
c,b[c])};e.hasClass=function(a,b){return(" "+a.className+" ").indexOf(" "+b+" ")>-1};e.addClass=function(a,b){if(!e.hasClass(a,b))a.className=a.className+" "+b};e.removeClass=function(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(?:\\s|$)"),"$1")};e.getPos=function(a){var b=function(a){for(var d={x:0,y:0};a&&!/^(?:body|html)$/i.test(a.tagName);)d.x+=a.offsetLeft,d.y+=a.offsetTop,a=a.offsetParent;return d}(a);a=function(a){for(var d={x:0,y:0};a&&!/^(?:body|html)$/i.test(a.tagName);)d.x+=
a.scrollLeft,d.y+=a.scrollTop,a=a.parentNode;return d}(a);return{x:b.x-a.x,y:b.y-a.y}};e.event={get:function(a,b){return a||(b||window).event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return a.which==3||a.button==2},getPos:function(a,b){b=b||window;a=a||b.event;var c=b.document;c=c.documentElement||c.body;a.touches&&a.touches.length&&(a=a.touches[0]);return{x:a.pageX||a.clientX+c.scrollLeft,y:a.pageY||a.clientY+c.scrollTop}},stop:function(a){a.stopPropagation&&
a.stopPropagation();a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1}};$jit.util=$jit.id=e;var m=function(a){a=a||{};var b=function(){for(var a in this)typeof this[a]!="function"&&(this[a]=e.unlink(this[a]));this.constructor=b;if(m.prototyping)return this;a=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return a},c;for(c in m.Mutators)a[c]&&(a=m.Mutators[c](a,a[c]),delete a[c]);e.extend(b,this);b.constructor=m;b.prototype=a;return b};m.Mutators=
{Implements:function(a,b){e.each(e.splat(b),function(b){m.prototyping=b;b=typeof b=="function"?new b:b;for(var d in b)d in a||(a[d]=b[d]);delete m.prototyping});return a}};e.extend(m,{inherit:function(a,b){for(var c in b){var d=b[c],f=a[c],h=e.type(d);f&&h=="function"?d!=f&&m.override(a,c,d):a[c]=h=="object"?e.merge(f,d):d}return a},override:function(a,b,c){var d=m.prototyping;d&&a[b]!=d[b]&&(d=null);a[b]=function(){var f=this.parent;this.parent=d?d[b]:a[b];var h=c.apply(this,arguments);this.parent=
f;return h}}});m.prototype.implement=function(){var a=this.prototype;e.each(Array.prototype.slice.call(arguments||[]),function(b){m.inherit(a,b)});return this};$jit.Class=m;$jit.json={prune:function(a,b){this.each(a,function(a,d){if(d==b&&a.children)delete a.children,a.children=[]})},getParent:function(a,b){if(a.id==b)return!1;var c=a.children;if(c&&c.length>0)for(var d=0;d<c.length;d++)if(c[d].id==b)return a;else{var f=this.getParent(c[d],b);if(f)return f}return!1},getSubtree:function(a,b){if(a.id==
b)return a;for(var c=0,d=a.children;c<d.length;c++){var f=this.getSubtree(d[c],b);if(f!=null)return f}return null},eachLevel:function(a,b,c,d){if(b<=c&&(d(a,b),a.children)){var f=0;for(a=a.children;f<a.length;f++)this.eachLevel(a[f],b+1,c,d)}},each:function(a,b){this.eachLevel(a,0,Number.MAX_VALUE,b)}};$jit.Trans={$extend:!0,linear:function(a){return a}};var w=$jit.Trans;(function(){var a=function(a,c){c=e.splat(c);return e.extend(a,{easeIn:function(d){return a(d,c)},easeOut:function(d){return 1-
a(1-d,c)},easeInOut:function(d){return d<=0.5?a(2*d,c)/2:(2-a(2*(1-d),c))/2}})};e.each({Pow:function(a,c){return Math.pow(a,c[0]||6)},Expo:function(a){return Math.pow(2,8*(a-1))},Circ:function(a){return 1-Math.sin(Math.acos(a))},Sine:function(a){return 1-Math.sin((1-a)*Math.PI/2)},Back:function(a,c){c=c[0]||1.618;return Math.pow(a,2)*((c+1)*a-c)},Bounce:function(a){for(var c,d=0,f=1;;d+=f,f/=2)if(a>=(7-4*d)/11){c=f*f-Math.pow((11-6*d-11*a)/4,2);break}return c},Elastic:function(a,c){return Math.pow(2,
10*--a)*Math.cos(20*a*Math.PI*(c[0]||1)/3)}},function(b,c){w[c]=a(b)});e.each(["Quad","Cubic","Quart","Quint"],function(b,c){w[b]=a(function(a){return Math.pow(a,[c+2])})})})();var C=new m({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=e.merge({duration:2500,fps:40,transition:w.Quart.easeInOut,compute:e.empty,complete:e.empty,link:"ignore"},a||{});return this},step:function(){var a=e.time(),b=this.opt;a<this.time+b.duration?(a=b.transition((a-this.time)/b.duration),b.compute(a)):
(this.timer=clearInterval(this.timer),b.compute(1),b.complete())},start:function(){if(!this.check())return this;this.time=0;this.startTimer();return this},startTimer:function(){var a=this,b=this.opt.fps;if(this.timer)return!1;this.time=e.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/b));return!0},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return!1;this.time=e.time()-this.time;this.timer=
clearInterval(this.timer);return!0},check:function(){if(!this.timer)return!0;if(this.opt.link=="cancel")return this.stopTimer(),!0;return!1}}),r=function(){for(var a=arguments,b=0,c=a.length,d={};b<c;b++){var f=r[a[b]];f.$extend?e.extend(d,f):d[a[b]]=f}return d};r.Canvas={$extend:!0,injectInto:"id",width:!1,height:!1,useCanvas:!1,withLabels:!0,background:!1};r.Tree={$extend:!0,orientation:"left",subtreeOffset:8,siblingOffset:5,indent:10,multitree:!1,align:"center"};r.Node={$extend:!1,overridable:!1,
type:"circle",color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:!1,autoWidth:!1,lineWidth:1,transform:!0,align:"center",angularWidth:1,span:1,CanvasStyles:{}};r.Edge={$extend:!1,overridable:!1,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};r.Fx={$extend:!0,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:!0};r.Label={$extend:!1,overridable:!1,type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",
color:"#fff"};r.Tips={$extend:!1,enable:!1,type:"auto",offsetX:20,offsetY:20,force:!1,onShow:e.empty,onHide:e.empty};r.NodeStyles={$extend:!1,enable:!1,type:"auto",stylesHover:!1,stylesClick:!1};r.Events={$extend:!1,enable:!1,enableForEdges:!1,type:"auto",onClick:e.empty,onRightClick:e.empty,onMouseMove:e.empty,onMouseEnter:e.empty,onMouseLeave:e.empty,onDragStart:e.empty,onDragMove:e.empty,onDragCancel:e.empty,onDragEnd:e.empty,onTouchStart:e.empty,onTouchMove:e.empty,onTouchEnd:e.empty,onMouseWheel:e.empty};
r.Navigation={$extend:!1,enable:!1,type:"auto",panning:!1,zooming:!1};r.Controller={$extend:!0,onBeforeCompute:e.empty,onAfterCompute:e.empty,onCreateLabel:e.empty,onPlaceLabel:e.empty,onComplete:e.empty,onBeforePlotLine:e.empty,onAfterPlotLine:e.empty,onBeforePlotNode:e.empty,onAfterPlotNode:e.empty,request:!1};var y={initialize:function(a,b){this.viz=b;this.canvas=b.canvas;this.config=b.config[a];this.nodeTypes=b.fx.nodeTypes;var c=this.config.type;this.labelContainer=(this.dom=c=="auto"?b.config.Label.type!=
"Native":c!="Native")&&b.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},initializePost:e.empty,setAsProperty:e.lambda(!1),isEnabled:function(){return this.config.enable},isLabel:function(a,b){a=e.event.get(a,b);var c=this.labelContainer,d=a.target||a.srcElement;if(d&&d.parentNode==c)return d;return!1}},z={onMouseUp:e.empty,onMouseDown:e.empty,onMouseMove:e.empty,onMouseOver:e.empty,onMouseOut:e.empty,onMouseWheel:e.empty,onTouchStart:e.empty,onTouchMove:e.empty,onTouchEnd:e.empty,
onTouchCancel:e.empty},G=new m({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=!1;this.registeredObjects=[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),b=this;a.oncontextmenu=e.lambda(!1);e.addEvents(a,{mouseup:function(a,c){var h=e.event.get(a,c);b.handleEvent("MouseUp",a,c,b.makeEventObject(a,c),e.event.isRightClick(h))},mousedown:function(a,c){var h=e.event.get(a,c);b.handleEvent("MouseDown",a,c,b.makeEventObject(a,c),e.event.isRightClick(h))},
mousemove:function(a,c){b.handleEvent("MouseMove",a,c,b.makeEventObject(a,c))},mouseover:function(a,c){b.handleEvent("MouseOver",a,c,b.makeEventObject(a,c))},mouseout:function(a,c){b.handleEvent("MouseOut",a,c,b.makeEventObject(a,c))},touchstart:function(a,c){b.handleEvent("TouchStart",a,c,b.makeEventObject(a,c))},touchmove:function(a,c){b.handleEvent("TouchMove",a,c,b.makeEventObject(a,c))},touchend:function(a,c){b.handleEvent("TouchEnd",a,c,b.makeEventObject(a,c))}});var c=function(a,c){var h=e.event.get(a,
c);h=e.event.getWheel(h);b.handleEvent("MouseWheel",a,c,h)};!document.getBoxObjectFor&&window.mozInnerScreenX==null?e.addEvent(a,"mousewheel",c):a.addEventListener("DOMMouseScroll",c,!1)},register:function(a){this.registeredObjects.push(a)},handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),b=a.shift(),c=0,d=this.registeredObjects,f=d.length;c<f;c++)d[c]["on"+b].apply(d[c],a)},makeEventObject:function(a,b){var c=this,d=this.viz.graph,f=this.viz.fx,h=f.nodeTypes,g=f.edgeTypes;return{pos:!1,
node:!1,edge:!1,contains:!1,getNodeCalled:!1,getEdgeCalled:!1,getPos:function(){var d=c.viz.canvas,f=d.getSize(),h=d.getPos(),g=d.translateOffsetX,p=d.translateOffsetY,q=d.scaleOffsetX;d=d.scaleOffsetY;var x=e.event.getPos(a,b);return this.pos={x:(x.x-h.x-f.width/2-g)*1/q,y:(x.y-h.y-f.height/2-p)*1/d}},getNode:function(){if(this.getNodeCalled)return this.node;this.getNodeCalled=!0;for(var a in d.nodes){var b=d.nodes[a],g=b&&h[b.getData("type")];if(g=g&&g.contains&&g.contains.call(f,b,this.getPos()))return this.contains=
g,c.node=this.node=b}return c.node=this.node=!1},getEdge:function(){if(this.getEdgeCalled)return this.edge;this.getEdgeCalled=!0;var a={},b;for(b in d.edges){var h=d.edges[b];a[b]=!0;for(var e in h)if(!(e in a)){var p=h[e],q=p&&g[p.getData("type")];if(q=q&&q.contains&&q.contains.call(f,p,this.getPos()))return this.contains=q,c.edge=this.edge=p}}return c.edge=this.edge=!1},getContains:function(){if(this.getNodeCalled)return this.contains;this.getNode();return this.contains}}}}),t={initializeExtras:function(){var a=
new G(this),b=this;e.each(["NodeStyles","Tips","Navigation","Events"],function(c){var d=new t.Classes[c](c,b);d.isEnabled()&&a.register(d);d.setAsProperty()&&(b[c.toLowerCase()]=d)})}};t.Classes={};t.Classes.Events=new m({Implements:[y,z],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;this.etypes=this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=!1},setAsProperty:e.lambda(!0),onMouseUp:function(a,b,c,d){a=e.event.get(a,b);if(!this.moved)if(d)this.config.onRightClick(this.hovered,
c,a);else this.config.onClick(this.pressed,c,a);if(this.pressed){if(this.moved)this.config.onDragEnd(this.pressed,c,a);else this.config.onDragCancel(this.pressed,c,a);this.pressed=this.moved=!1}},onMouseOut:function(a,b,c){var d=e.event.get(a,b),f;if(this.dom&&(f=this.isLabel(a,b)))this.config.onMouseLeave(this.viz.graph.getNode(f.id),c,d),this.hovered=!1;else{a=d.relatedTarget;for(b=this.canvas.getElement();a&&a.parentNode;){if(b==a.parentNode)return;a=a.parentNode}if(this.hovered)this.config.onMouseLeave(this.hovered,
c,d),this.hovered=!1}},onMouseOver:function(a,b,c){var d=e.event.get(a,b),f;if(this.dom&&(f=this.isLabel(a,b)))this.hovered=this.viz.graph.getNode(f.id),this.config.onMouseEnter(this.hovered,c,d)},onMouseMove:function(a,b,c){a=e.event.get(a,b);if(this.pressed)this.moved=!0,this.config.onDragMove(this.pressed,c,a);else if(this.dom)this.config.onMouseMove(this.hovered,c,a);else{if(this.hovered){b=this.hovered;var d=b.nodeFrom?this.etypes[b.getData("type")]:this.ntypes[b.getData("type")];if(d&&d.contains&&
d.contains.call(this.fx,b,c.getPos())){this.config.onMouseMove(b,c,a);return}else this.config.onMouseLeave(b,c,a),this.hovered=!1}if(this.hovered=c.getNode()||this.config.enableForEdges&&c.getEdge())this.config.onMouseEnter(this.hovered,c,a);else this.config.onMouseMove(!1,c,a)}},onMouseWheel:function(a,b,c){this.config.onMouseWheel(c,e.event.get(a,b))},onMouseDown:function(a,b,c){a=e.event.get(a,b);this.pressed=c.getNode()||this.config.enableForEdges&&c.getEdge();this.config.onDragStart(this.pressed,
c,a)},onTouchStart:function(a,b,c){a=e.event.get(a,b);this.touched=c.getNode()||this.config.enableForEdges&&c.getEdge();this.config.onTouchStart(this.touched,c,a)},onTouchMove:function(a,b,c){a=e.event.get(a,b);if(this.touched)this.touchMoved=!0,this.config.onTouchMove(this.touched,c,a)},onTouchEnd:function(a,b,c){a=e.event.get(a,b);if(this.touched){if(this.touchMoved)this.config.onTouchEnd(this.touched,c,a);else this.config.onTouchCancel(this.touched,c,a);this.touched=this.touchMoved=!1}}});t.Classes.Tips=
new m({Implements:[y,z],initializePost:function(){if(document.body){var a=e("_tooltip")||document.createElement("div");a.id="_tooltip";a.className="tip";e.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);this.tip=a;this.node=!1}},setAsProperty:e.lambda(!0),onMouseOut:function(a,b){if(this.dom&&this.isLabel(a,b))this.hide(!0);else{for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.hide(!1)}},
onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b)))this.node=this.viz.graph.getNode(c.id),this.config.onShow(this.tip,this.node,c)},onMouseMove:function(a,b,c){this.dom&&this.isLabel(a,b)&&this.setTooltipPosition(e.event.getPos(a,b));if(!this.dom){var d=c.getNode();if(d){if(this.config.force||!this.node||this.node.id!=d.id)this.node=d,this.config.onShow(this.tip,d,c.getContains());this.setTooltipPosition(e.event.getPos(a,b))}else this.hide(!0)}},setTooltipPosition:function(a){var b=
this.tip,c=b.style,d=this.config;c.display="";var f={height:document.body.clientHeight,width:document.body.clientWidth};b={width:b.offsetWidth,height:b.offsetHeight};var h=d.offsetX;d=d.offsetY;c.top=(a.y+d+b.height>f.height?a.y-b.height-d:a.y+d)+"px";c.left=(a.x+b.width+h>f.width?a.x-b.width-h:a.x+h)+"px"},hide:function(a){this.tip.style.display="none";a&&this.config.onHide()}});t.Classes.NodeStyles=new m({Implements:[y,z],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;
this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=!1;this.fx.nodeFxAnimation=new C;this.move=this.down=!1},onMouseOut:function(a,b){this.down=this.move=!1;if(this.hoveredNode){this.dom&&this.isLabel(a,b)&&this.toggleStylesOnHover(this.hoveredNode,!1);for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.toggleStylesOnHover(this.hoveredNode,!1);this.hoveredNode=
!1}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b)))if(c=this.viz.graph.getNode(c.id),!c.selected)this.hoveredNode=c,this.toggleStylesOnHover(this.hoveredNode,!0)},onMouseDown:function(a,b,c,d){if(!d){var f;if(this.dom&&(f=this.isLabel(a,b)))this.down=this.viz.graph.getNode(f.id);else if(!this.dom)this.down=c.getNode();this.move=!1}},onMouseUp:function(a,b,c,d){if(!d){if(!this.move)this.onClick(c.getNode());this.down=this.move=!1}},getRestoredStyles:function(a,b){var c={},d=this["nodeStylesOn"+
b],f;for(f in d)c[f]=a.styles["$"+f];return c},toggleStylesOnHover:function(a,b){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",a,b)},toggleStylesOnClick:function(a,b){this.nodeStylesOnClick&&this.toggleStylesOn("Click",a,b)},toggleStylesOn:function(a,b,c){var d=this.viz;if(c){if(!b.styles)b.styles=e.merge(b.data,{});for(var f in this["nodeStylesOn"+a])c="$"+f,c in b.styles||(b.styles[c]=b.getData(f));d.fx.nodeFx(e.extend({elements:{id:b.id,properties:this["nodeStylesOn"+a]},transition:w.Quart.easeOut,
duration:300,fps:40},this.config))}else a=this.getRestoredStyles(b,a),d.fx.nodeFx(e.extend({elements:{id:b.id,properties:a},transition:w.Quart.easeOut,duration:300,fps:40},this.config))},onClick:function(a){if(a){var b=this.nodeStylesOnClick;if(b)a.selected?(this.toggleStylesOnClick(a,!1),delete a.selected):(this.viz.graph.eachNode(function(a){if(a.selected){for(var d in b)a.setData(d,a.styles["$"+d],"end");delete a.selected}}),this.toggleStylesOnClick(a,!0),a.selected=!0,delete a.hovered,this.hoveredNode=
!1)}},onMouseMove:function(a,b,c){if(this.down)this.move=!0;if(!this.dom||!this.isLabel(a,b)){var d=this.nodeStylesOnHover;if(d&&!this.dom){if(this.hoveredNode&&(a=this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,c.getPos()))return;c=c.getNode();if((this.hoveredNode||c)&&!c.hovered)if(c&&!c.selected)this.fx.nodeFxAnimation.stopTimer(),this.viz.graph.eachNode(function(a){if(a.hovered&&!a.selected){for(var c in d)a.setData(c,a.styles["$"+c],"end");
delete a.hovered}}),c.hovered=!0,this.hoveredNode=c,this.toggleStylesOnHover(c,!0);else if(this.hoveredNode&&!this.hoveredNode.selected)this.fx.nodeFxAnimation.stopTimer(),this.toggleStylesOnHover(this.hoveredNode,!1),delete this.hoveredNode.hovered,this.hoveredNode=!1}}}});t.Classes.Navigation=new m({Implements:[y,z],initializePost:function(){this.pressed=this.pos=!1},onMouseWheel:function(a,b,c){this.config.zooming&&(e.event.stop(e.event.get(a,b)),a=1+c*(this.config.zooming/1E3),this.canvas.scale(a,
a))},onMouseDown:function(a,b,c){if(this.config.panning&&!(this.config.panning=="avoid nodes"&&c.getNode())){this.pressed=!0;this.pos=c.getPos();a=this.canvas;b=a.translateOffsetX;c=a.translateOffsetY;var d=a.scaleOffsetY;this.pos.x*=a.scaleOffsetX;this.pos.x+=b;this.pos.y*=d;this.pos.y+=c}},onMouseMove:function(a,b,c){if(this.config.panning&&this.pressed&&!(this.config.panning=="avoid nodes"&&c.getNode())){a=this.pos;c=c.getPos();var d=this.canvas,f=d.translateOffsetX,h=d.translateOffsetY;b=d.scaleOffsetX;
d=d.scaleOffsetY;c.x*=b;c.y*=d;c.x+=f;c.y+=h;f=c.x-a.x;a=c.y-a.y;this.pos=c;this.canvas.translate(f*1/b,a*1/d)}},onMouseUp:function(){if(this.config.panning)this.pressed=!1}});var u;(function(){function a(a,b){var h=document.createElement(a),g;for(g in b)typeof b[g]=="object"?e.extend(h[g],b[g]):h[g]=b[g];a=="canvas"&&!c&&G_vmlCanvasManager&&(h=G_vmlCanvasManager.initElement(document.body.appendChild(h)));return h}var b=typeof HTMLCanvasElement,c=b=="object"||b=="function";$jit.Canvas=u=new m({canvases:[],
pos:!1,element:!1,labelContainer:!1,translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(d,c){this.viz=d;this.opt=c;var b=e.type(c.injectInto)=="string"?c.injectInto:c.injectInto.id,g=b+"-label",j=e(b),i=c.width||j.offsetWidth,k=c.height||j.offsetHeight;this.id=b;var l={injectInto:b,width:i,height:k};this.element=a("div",{id:b+"-canvaswidget",style:{position:"relative",width:i+"px",height:k+"px"}});this.labelContainer=this.createLabelContainer(c.Label.type,g,l);
this.canvases.push(new u.Base({config:e.extend({idSuffix:"-canvas"},l),plot:function(){d.fx.plot()},resize:function(){d.refresh()}}));if(b=c.background)l=new u.Background[b.type](d,e.extend(b,l)),this.canvases.push(new u.Base(l));for(l=this.canvases.length;l--;)this.element.appendChild(this.canvases[l].canvas),l>0&&this.canvases[l].plot();this.element.appendChild(this.labelContainer);j.appendChild(this.element);var p=null,q=this;e.addEvent(window,"scroll",function(){clearTimeout(p);p=setTimeout(function(){q.getPos(!0)},
500)})},getCtx:function(a){return this.canvases[a||0].getCtx()},getConfig:function(){return this.opt},getElement:function(){return this.element},getSize:function(a){return this.canvases[a||0].getSize()},resize:function(a,c){this.getPos(!0);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;for(var b=0,g=this.canvases.length;b<g;b++)this.canvases[b].resize(a,c);b=this.element.style;b.width=a+"px";b.height=c+"px";if(this.labelContainer)this.labelContainer.style.width=
a+"px"},translate:function(a,c,b){this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=c*this.scaleOffsetY;for(var g=0,e=this.canvases.length;g<e;g++)this.canvases[g].translate(a,c,b)},scale:function(a,c){var b=this.scaleOffsetX*a,g=this.scaleOffsetY*c,e=this.translateOffsetX*(a-1)/b,i=this.translateOffsetY*(c-1)/g;this.scaleOffsetX=b;this.scaleOffsetY=g;b=0;for(g=this.canvases.length;b<g;b++)this.canvases[b].scale(a,c,!0);this.translate(e,i,!1)},getPos:function(a){if(a||!this.pos)return this.pos=
e.getPos(this.getElement());return this.pos},clear:function(a){this.canvases[a||0].clear()},path:function(a,c){var b=this.canvases[0].getCtx();b.beginPath();c(b);b[a]();b.closePath()},createLabelContainer:function(d,c,b){if(d=="HTML"||d=="Native")return a("div",{id:c,style:{overflow:"visible",position:"absolute",top:0,left:0,width:b.width+"px",height:0}});else if(d=="SVG"){d=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");d.setAttribute("width",b.width);d.setAttribute("height",b.height);
var g=d.style;g.position="absolute";g.left=g.top="0px";g=document.createElementNS("http://www.w3.org/2000/svg","svg:g");g.setAttribute("width",b.width);g.setAttribute("height",b.height);g.setAttribute("x",0);g.setAttribute("y",0);g.setAttribute("id",c);d.appendChild(g);return d}}});u.Base=new m({translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a){this.viz=a;this.opt=a.config;this.size=!1;this.createCanvas();this.translateToCenter()},createCanvas:function(){var d=
this.opt,b=d.width,c=d.height;this.canvas=a("canvas",{id:d.injectInto+d.idSuffix,width:b,height:c,style:{position:"absolute",top:0,left:0,width:b+"px",height:c+"px"}})},getCtx:function(){if(!this.ctx)return this.ctx=this.canvas.getContext("2d");return this.ctx},getSize:function(){if(this.size)return this.size;var a=this.canvas;return this.size={width:a.width,height:a.height}},translateToCenter:function(a){var b=this.getSize(),c=a?b.width-a.width-this.translateOffsetX*2:b.width;height=a?b.height-a.height-
this.translateOffsetY*2:b.height;b=this.getCtx();a&&b.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);b.translate(c/2,height/2)},resize:function(a,b){var h=this.getSize(),g=this.canvas,e=g.style;this.size=!1;g.width=a;g.height=b;e.width=a+"px";e.height=b+"px";c?this.translateToCenter():this.translateToCenter(h);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(a,b,this)},translate:function(a,b,c){var g=this.scaleOffsetY;this.translateOffsetX+=
a*this.scaleOffsetX;this.translateOffsetY+=b*g;this.getCtx().translate(a,b);!c&&this.plot()},scale:function(a,b,c){this.scaleOffsetX*=a;this.scaleOffsetY*=b;this.getCtx().scale(a,b);!c&&this.plot()},clear:function(){var a=this.getSize(),b=this.translateOffsetX,c=this.translateOffsetY,g=this.scaleOffsetX,e=this.scaleOffsetY;this.getCtx().clearRect((-a.width/2-b)*1/g,(-a.height/2-c)*1/e,a.width*1/g,a.height*1/e)},plot:function(){this.clear();this.viz.plot(this)}});u.Background={};u.Background.Circles=
new m({initialize:function(a,b){this.viz=a;this.config=e.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,CanvasStyles:{},offset:0},b)},resize:function(a,b,c){this.plot(c)},plot:function(a){a=a.getCtx();var b=this.config,c=b.CanvasStyles,g;for(g in c)a[g]=c[g];g=b.numberOfCircles;b=b.levelDistance;for(c=1;c<=g;c++)a.beginPath(),a.arc(0,0,b*c,0,2*Math.PI,!1),a.stroke(),a.closePath()}})})();var s=function(a,b){this.theta=a;this.rho=b};$jit.Polar=s;s.prototype={getc:function(a){return this.toComplex(a)},
getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,b){this.rho=Math.sqrt(a*a+b*b);this.theta=Math.atan2(b,a);this.theta<0&&(this.theta+=Math.PI*2)},setp:function(a,b){this.theta=a;this.rho=b},clone:function(){return new s(this.theta,this.rho)},toComplex:function(a){var b=Math.cos(this.theta)*this.rho,c=Math.sin(this.theta)*this.rho;if(a)return{x:b,y:c};return new o(b,c)},add:function(a){return new s(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new s(this.theta,
this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},$add:function(a){this.theta+=a.theta;this.rho+=a.rho;return this},$madd:function(a){this.theta=(this.theta+a.theta)%(Math.PI*2);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},interpolate:function(a,b){var c=Math.PI,d=c*2,f=function(a){return a<0?a%d+d:a%d},h=this.theta,g=a.theta,e=Math.abs(h-g);return{theta:e==c?h>g?f(g+(h-d-g)*b):f(g-d+(h-g)*b):e>=c?h>g?f(g+(h-d-g)*b):f(g-d+(h-(g-d))*b):f(g+(h-
g)*b),rho:(this.rho-a.rho)*b+a.rho}}};s.KER=new s(0,0);var o=function(a,b){this.x=a;this.y=b};$jit.Complex=o;o.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},set:function(a){a=a.getc(!0);this.x=a.x;this.y=a.y},setc:function(a,b){this.x=a;this.y=b},setp:function(a,b){this.x=Math.cos(a)*b;this.y=Math.sin(a)*b},clone:function(){return new o(this.x,this.y)},toPolar:function(a){var b=this.norm(),c=Math.atan2(this.y,this.x);c<0&&(c+=Math.PI*2);if(a)return{theta:c,rho:b};
return new s(c,b)},norm:function(){return Math.sqrt(this.squaredNorm())},squaredNorm:function(){return this.x*this.x+this.y*this.y},add:function(a){return new o(this.x+a.x,this.y+a.y)},prod:function(a){return new o(this.x*a.x-this.y*a.y,this.y*a.x+this.x*a.y)},conjugate:function(){return new o(this.x,-this.y)},scale:function(a){return new o(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var b=this.x,c=
this.y;this.x=b*a.x-c*a.y;this.y=c*a.x+b*a.y;return this},$conjugate:function(){this.y=-this.y;return this},$scale:function(a){this.x*=a;this.y*=a;return this},$div:function(a){var b=this.x,c=this.y,d=a.squaredNorm();this.x=b*a.x+c*a.y;this.y=c*a.x-b*a.y;return this.$scale(1/d)}};o.KER=new o(0,0);$jit.Graph=new m({initialize:function(a,b,c,d){this.Node=b;this.Edge=c;this.Label=d;this.opt=e.merge({complex:!1,Node:{}},a||{});this.nodes={};this.edges={};var f=this;this.nodeList={};for(var h in v)f.nodeList[h]=
function(a){return function(){var b=Array.prototype.slice.call(arguments);f.eachNode(function(c){c[a].apply(c,b)})}}(h)},getNode:function(a){if(this.hasNode(a))return this.nodes[a];return!1},getByName:function(a){for(var b in this.nodes){var c=this.nodes[b];if(c.name==a)return c}return!1},getAdjacence:function(a,b){if(a in this.edges)return this.edges[a][b];return!1},addNode:function(a){if(!this.nodes[a.id]){var b=this.edges[a.id]={};this.nodes[a.id]=new n.Node(e.extend({id:a.id,name:a.name,data:e.merge(a.data||
{},{}),adjacencies:b},this.opt.Node),this.opt.complex,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},addAdjacence:function(a,b,c){this.hasNode(a.id)||this.addNode(a);this.hasNode(b.id)||this.addNode(b);a=this.nodes[a.id];b=this.nodes[b.id];if(!a.adjacentTo(b)){var d=this.edges[a.id]=this.edges[a.id]||{},f=this.edges[b.id]=this.edges[b.id]||{};d[b.id]=f[a.id]=new n.Adjacence(a,b,c,this.Edge,this.Label);return d[b.id]}return this.edges[a.id][b.id]},removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];
var b=this.edges[a],c;for(c in b)delete this.edges[c][a];delete this.edges[a]}},removeAdjacence:function(a,b){delete this.edges[a][b];delete this.edges[b][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes={};this.edges={}}});var n=$jit.Graph,v;(function(){var a=function(a,b,c,g,e){var i;c=c||"current";if(c=="current")i=this.data;else if(c=="start")i=this.startData;else if(c=="end")i=this.endData;a="$"+(a?a+"-":"")+b;if(g)return i[a];if(!this.Config.overridable)return e[b]||
0;return a in i?i[a]:a in this.data?this.data[a]:e[b]||0},b=function(a,b,c,g){g=g||"current";var e;if(g=="current")e=this.data;else if(g=="start")e=this.startData;else if(g=="end")e=this.endData;e["$"+(a?a+"-":"")+b]=c},c=function(a,b){a="$"+(a?a+"-":"");var c=this;e.each(b,function(b){b=a+b;delete c.data[b];delete c.endData[b];delete c.startData[b]})};v={getData:function(b,c,h){return a.call(this,"",b,c,h,this.Config)},setData:function(a,c,h){b.call(this,"",a,c,h)},setDataset:function(a,b){a=e.splat(a);
for(var c in b)for(var g=0,j=e.splat(b[c]),i=a.length;g<i;g++)this.setData(c,j[g],a[g])},removeData:function(){c.call(this,"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(b,c,h){return a.call(this,"canvas",b,c,h,this.Config.CanvasStyles)},setCanvasStyle:function(a,c,h){b.call(this,"canvas",a,c,h)},setCanvasStyles:function(a,b){a=e.splat(a);for(var c in b)for(var g=0,j=e.splat(b[c]),i=a.length;g<i;g++)this.setCanvasStyle(c,j[g],a[g])},removeCanvasStyle:function(){c.call(this,"canvas",
Array.prototype.slice.call(arguments))},getLabelData:function(b,c,h){return a.call(this,"label",b,c,h,this.Label)},setLabelData:function(a,c,h){b.call(this,"label",a,c,h)},setLabelDataset:function(a,b){a=e.splat(a);for(var c in b)for(var g=0,j=e.splat(b[c]),i=a.length;g<i;g++)this.setLabelData(c,j[g],a[g])},removeLabelData:function(){c.call(this,"label",Array.prototype.slice.call(arguments))}}})();n.Node=new m({initialize:function(a,b,c,d,f){b={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},
selected:!1,drawn:!1,exist:!1,angleSpan:{begin:0,end:0},pos:b&&new o(0,0)||new s(0,0),startPos:b&&new o(0,0)||new s(0,0),endPos:b&&new o(0,0)||new s(0,0)};e.extend(this,e.extend(b,a));this.Config=this.Node=c;this.Edge=d;this.Label=f},adjacentTo:function(a){return a.id in this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if(a=="current")return this.pos;else if(a=="end")return this.endPos;else if(a=="start")return this.startPos},setPos:function(a,
b){b=b||"current";var c;if(b=="current")c=this.pos;else if(b=="end")c=this.endPos;else if(b=="start")c=this.startPos;c.set(a)}});n.Node.implement(v);n.Adjacence=new m({initialize:function(a,b,c,d,f){this.nodeFrom=a;this.nodeTo=b;this.data=c||{};this.startData={};this.endData={};this.Config=this.Edge=d;this.Label=f}});n.Adjacence.implement(v);n.Util={filter:function(a){if(!a||e.type(a)!="string")return function(){return!0};var b=a.split(" ");return function(a){for(var d=0;d<b.length;d++)if(a[b[d]])return!1;
return!0}},getNode:function(a,b){return a.nodes[b]},eachNode:function(a,b,c){c=this.filter(c);for(var d in a.nodes)c(a.nodes[d])&&b(a.nodes[d])},eachAdjacency:function(a,b,c){var d=a.adjacencies;c=this.filter(c);for(var f in d){var h=d[f];if(c(h)){if(h.nodeFrom!=a){var g=h.nodeFrom;h.nodeFrom=h.nodeTo;h.nodeTo=g}b(h,f)}}},computeLevels:function(a,b,c,d){c=c||0;var f=this.filter(d);this.eachNode(a,function(a){a._flag=!1;a._depth=-1},d);a=a.getNode(b);a._depth=c;for(var h=[a];h.length!=0;){var g=h.pop();
g._flag=!0;this.eachAdjacency(g,function(a){a=a.nodeTo;if(a._flag==!1&&f(a)){if(a._depth<0)a._depth=g._depth+1+c;h.unshift(a)}},d)}},eachBFS:function(a,b,c,d){var f=this.filter(d);this.clean(a);for(var h=[a.getNode(b)];h.length!=0;)a=h.pop(),a._flag=!0,c(a,a._depth),this.eachAdjacency(a,function(a){a=a.nodeTo;if(a._flag==!1&&f(a))a._flag=!0,h.unshift(a)},d)},eachLevel:function(a,b,c,d,f){var h=a._depth,g=this.filter(f),e=this;c=c===!1?Number.MAX_VALUE-h:c;(function k(a,b,c){var f=a._depth;f>=b&&f<=
c&&g(a)&&d(a,f);f<c&&e.eachAdjacency(a,function(a){a=a.nodeTo;a._depth>f&&k(a,b,c)})})(a,b+h,c+h)},eachSubgraph:function(a,b,c){this.eachLevel(a,0,!1,b,c)},eachSubnode:function(a,b,c){this.eachLevel(a,1,1,b,c)},anySubnode:function(a,b,c){var d=!1;b=b||e.lambda(!0);var f=e.type(b)=="string"?function(a){return a[b]}:b;this.eachSubnode(a,function(a){f(a)&&(d=!0)},c);return d},getSubnodes:function(a,b,c){var d=[];b=b||0;var f;e.type(b)=="array"?(f=b[0],b=b[1]):(f=b,b=Number.MAX_VALUE-a._depth);this.eachLevel(a,
f,b,function(a){d.push(a)},c);return d},getParents:function(a){var b=[];this.eachAdjacency(a,function(c){c=c.nodeTo;c._depth<a._depth&&b.push(c)});return b},isDescendantOf:function(a,b){if(a.id==b)return!0;for(var c=this.getParents(a),d=!1,f=0;!d&&f<c.length;f++)d=d||this.isDescendantOf(c[f],b);return d},clean:function(a){this.eachNode(a,function(a){a._flag=!1})},getClosestNodeToOrigin:function(a,b,c){return this.getClosestNodeToPos(a,s.KER,b,c)},getClosestNodeToPos:function(a,b,c,d){var f=null;c=
c||"current";b=b&&b.getc(!0)||o.KER;var h=function(a,b){var c=a.x-b.x,d=a.y-b.y;return c*c+d*d};this.eachNode(a,function(a){f=f==null||h(a.getPos(c).getc(!0),b)<h(f.getPos(c).getc(!0),b)?a:f},d);return f}};e.each(["getNode","eachNode","computeLevels","eachBFS","clean","getClosestNodeToPos","getClosestNodeToOrigin"],function(a){n.prototype[a]=function(){return n.Util[a].apply(n.Util,[this].concat(Array.prototype.slice.call(arguments)))}});e.each(["eachAdjacency","eachLevel","eachSubgraph","eachSubnode",
"anySubnode","getSubnodes","getParents","isDescendantOf"],function(a){n.Node.prototype[a]=function(){return n.Util[a].apply(n.Util,[this].concat(Array.prototype.slice.call(arguments)))}});n.Op={options:{type:"nothing",duration:2E3,hideLabels:!0,fps:30},initialize:function(a){this.viz=a},removeNode:function(a,b){var c=this.viz,d=e.merge(this.options,c.controller,b),f=e.splat(a),h,g,j;switch(d.type){case "nothing":for(h=0;h<f.length;h++)c.graph.removeNode(f[h]);break;case "replot":this.removeNode(f,
{type:"nothing"});c.labels.clearLabels();c.refresh(!0);break;case "fade:seq":case "fade":g=this;for(h=0;h<f.length;h++)j=c.graph.getNode(f[h]),j.setData("alpha",0,"end");c.fx.animate(e.merge(d,{modes:["node-property:alpha"],onComplete:function(){g.removeNode(f,{type:"nothing"});c.labels.clearLabels();c.reposition();c.fx.animate(e.merge(d,{modes:["linear"]}))}}));break;case "fade:con":g=this;for(h=0;h<f.length;h++)j=c.graph.getNode(f[h]),j.setData("alpha",0,"end"),j.ignore=!0;c.reposition();c.fx.animate(e.merge(d,
{modes:["node-property:alpha","linear"],onComplete:function(){g.removeNode(f,{type:"nothing"})}}));break;case "iter":g=this;c.fx.sequence({condition:function(){return f.length!=0},step:function(){g.removeNode(f.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/f.length)});break;default:this.doError()}},removeEdge:function(a,b){var c=this.viz,d=e.merge(this.options,c.controller,b),f=e.type(a[0])=="string"?[a]:a,h,g,j;switch(d.type){case "nothing":for(h=
0;h<f.length;h++)c.graph.removeAdjacence(f[h][0],f[h][1]);break;case "replot":this.removeEdge(f,{type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":g=this;for(h=0;h<f.length;h++)(j=c.graph.getAdjacence(f[h][0],f[h][1]))&&j.setData("alpha",0,"end");c.fx.animate(e.merge(d,{modes:["edge-property:alpha"],onComplete:function(){g.removeEdge(f,{type:"nothing"});c.reposition();c.fx.animate(e.merge(d,{modes:["linear"]}))}}));break;case "fade:con":g=this;for(h=0;h<f.length;h++)if(j=c.graph.getAdjacence(f[h][0],
f[h][1]))j.setData("alpha",0,"end"),j.ignore=!0;c.reposition();c.fx.animate(e.merge(d,{modes:["edge-property:alpha","linear"],onComplete:function(){g.removeEdge(f,{type:"nothing"})}}));break;case "iter":g=this;c.fx.sequence({condition:function(){return f.length!=0},step:function(){g.removeEdge(f.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/f.length)});break;default:this.doError()}},sum:function(a,b){var c=this.viz,d=e.merge(this.options,
c.controller,b),f=c.root,h;c.root=b.id||c.root;switch(d.type){case "nothing":h=c.construct(a);h.eachNode(function(a){a.eachAdjacency(function(a){c.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data)})});break;case "replot":c.refresh(!0);this.sum(a,{type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;h=c.construct(a);var g=!this.preprocessSum(h)?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];c.reposition();d.type!="fade:con"?c.fx.animate(e.merge(d,
{modes:["linear"],onComplete:function(){c.fx.animate(e.merge(d,{modes:g,onComplete:function(){d.onComplete()}}))}})):(c.graph.eachNode(function(a){a.id!=f&&a.pos.getp().equals(s.KER)&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))}),c.fx.animate(e.merge(d,{modes:["linear"].concat(g)})));break;default:this.doError()}},morph:function(a,b,c){var d=this.viz,f=e.merge(this.options,d.controller,b),h=d.root,g;d.root=b.id||d.root;switch(f.type){case "nothing":g=d.construct(a);g.eachNode(function(a){var b=
d.graph.hasNode(a.id);a.eachAdjacency(function(a){var b=!!d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id);d.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data);if(b)for(var c in b=d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id),a.data||{})b.data[c]=a.data[c]});if(b)for(var c in b=d.graph.getNode(a.id),a.data||{})b.data[c]=a.data[c]});d.graph.eachNode(function(a){a.eachAdjacency(function(a){g.getAdjacence(a.nodeFrom.id,a.nodeTo.id)||d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)});g.hasNode(a.id)||
d.graph.removeNode(a.id)});break;case "replot":d.labels.clearLabels(!0);this.morph(a,{type:"nothing"});d.refresh(!0);d.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;g=d.construct(a);var j=c&&"node-property"in c&&e.map(e.splat(c["node-property"]),function(a){return"$"+a});d.graph.eachNode(function(a){var b=g.getNode(a.id);if(b)for(var c in b=b.data,b)j&&e.indexOf(j,c)>-1?a.endData[c]=b[c]:a.data[c]=b[c];else a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",
0,"end"),a.ignore=!0});d.graph.eachNode(function(a){a.ignore||a.eachAdjacency(function(a){if(!a.nodeFrom.ignore&&!a.nodeTo.ignore){var b=g.getNode(a.nodeFrom.id);a=g.getNode(a.nodeTo.id);b.adjacentTo(a)||(a=d.graph.getAdjacence(b.id,a.id),i=!0,a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"))}})});var i=this.preprocessSum(g);a=!i?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];a[0]+=c&&"node-property"in c?":"+e.splat(c["node-property"]).join(":"):
"";a[1]=(a[1]||"edge-property:alpha")+(c&&"edge-property"in c?":"+e.splat(c["edge-property"]).join(":"):"");c&&"label-property"in c&&a.push("label-property:"+e.splat(c["label-property"]).join(":"));d.reposition();d.graph.eachNode(function(a){a.id!=h&&a.pos.getp().equals(s.KER)&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))});d.fx.animate(e.merge(f,{modes:["polar"].concat(a),onComplete:function(){d.graph.eachNode(function(a){a.ignore&&d.graph.removeNode(a.id)});d.graph.eachNode(function(a){a.eachAdjacency(function(a){a.ignore&&
d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)})});f.onComplete()}}))}},contract:function(a,b){var c=this.viz;if(!a.collapsed&&a.anySubnode(e.lambda(!0)))b=e.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]}),a.collapsed=!0,function f(a){a.eachSubnode(function(a){a.ignore=!0;a.setData("alpha",0,b.type=="animate"?"end":"current");f(a)})}(a),b.type=="animate"?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),function h(b){b.eachSubnode(function(b){b.setPos(a.getPos("end"),
"end");h(b)})}(a),c.fx.animate(b)):b.type=="replot"&&c.refresh()},expand:function(a,b){if("collapsed"in a){var c=this.viz;b=e.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]});delete a.collapsed;(function f(a){a.eachSubnode(function(a){delete a.ignore;a.setData("alpha",1,b.type=="animate"?"end":"current");f(a)})})(a);b.type=="animate"?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),c.fx.animate(b)):b.type=="replot"&&c.refresh()}},preprocessSum:function(a){var b=
this.viz;a.eachNode(function(a){b.graph.hasNode(a.id)||(b.graph.addNode(a),a=b.graph.getNode(a.id),a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end"))});var c=!1;a.eachNode(function(a){a.eachAdjacency(function(a){var d=b.graph.getNode(a.nodeFrom.id),g=b.graph.getNode(a.nodeTo.id);d.adjacentTo(g)||(a=b.graph.addAdjacence(d,g,a.data),d.startAlpha==d.endAlpha&&g.startAlpha==g.endAlpha&&(c=!0,a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end")))})});
return c}};var A={none:{render:e.empty,contains:e.lambda(!1)},circle:{render:function(a,b,c,d){d=d.getCtx();d.beginPath();d.arc(b.x,b.y,c,0,Math.PI*2,!0);d.closePath();d[a]()},contains:function(a,b,c){var d=a.x-b.x;a=a.y-b.y;return d*d+a*a<=c*c}},ellipse:{render:function(a,b,c,d,f){f=f.getCtx();d/=2;c/=2;f.save();f.scale(c/d,d/c);f.beginPath();f.arc(b.x*(d/c),b.y*(c/d),d,0,Math.PI*2,!0);f.closePath();f[a]();f.restore()},contains:function(a,b,c,d){c/=2;d/=2;c=(c+d)/2;d=a.x-b.x;a=a.y-b.y;return d*d+
a*a<=c*c}},square:{render:function(a,b,c,d){d.getCtx()[a+"Rect"](b.x-c,b.y-c,2*c,2*c)},contains:function(a,b,c){return Math.abs(b.x-a.x)<=c&&Math.abs(b.y-a.y)<=c}},rectangle:{render:function(a,b,c,d,f){f.getCtx()[a+"Rect"](b.x-c/2,b.y-d/2,c,d)},contains:function(a,b,c,d){return Math.abs(b.x-a.x)<=c/2&&Math.abs(b.y-a.y)<=d/2}},triangle:{render:function(a,b,c,d){d=d.getCtx();var f=b.x,h=b.y-c,g=f-c;b=b.y+c;c=f+c;d.beginPath();d.moveTo(f,h);d.lineTo(g,b);d.lineTo(c,b);d.closePath();d[a]()},contains:function(a,
b,c){return A.circle.contains(a,b,c)}},star:{render:function(a,b,c,d){d=d.getCtx();var f=Math.PI/5;d.save();d.translate(b.x,b.y);d.beginPath();d.moveTo(c,0);for(b=0;b<9;b++)d.rotate(f),b%2==0?d.lineTo(c/0.525731*0.200811,0):d.lineTo(c,0);d.closePath();d[a]();d.restore()},contains:function(a,b,c){return A.circle.contains(a,b,c)}}},E={line:{render:function(a,b,c){c=c.getCtx();c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()},contains:function(a,b,c,d){var f=Math.min,h=Math.max,g=f(a.x,b.x),
e=h(a.x,b.x);f=f(a.y,b.y);h=h(a.y,b.y);if(c.x>=g&&c.x<=e&&c.y>=f&&c.y<=h){if(Math.abs(b.x-a.x)<=d)return!0;return Math.abs((b.y-a.y)/(b.x-a.x)*(c.x-a.x)+a.y-c.y)<=d}return!1}},arrow:{render:function(a,b,c,d,f){f=f.getCtx();d&&(d=a,a=b,b=d);d=new o(b.x-a.x,b.y-a.y);d.$scale(c/d.norm());c=new o(b.x-d.x,b.y-d.y);var h=new o(-d.y/2,d.x/2);d=c.add(h);c=c.$add(h.$scale(-1));f.beginPath();f.moveTo(a.x,a.y);f.lineTo(b.x,b.y);f.stroke();f.beginPath();f.moveTo(d.x,d.y);f.lineTo(c.x,c.y);f.lineTo(b.x,b.y);f.closePath();
f.fill()},contains:function(a,b,c,d){return E.line.contains(a,b,c,d)}},hyperline:{render:function(a,b,c,d){function f(a,b){return a<b?a+Math.PI>b?!1:!0:b+Math.PI>a?!0:!1}d=d.getCtx();var h=function(a,b){var c=a.x*b.y-a.y*b.x,d=a.squaredNorm(),f=b.squaredNorm();if(c==0)return{x:0,y:0,ratio:-1};var h=(a.y*f-b.y*d+a.y-b.y)/c;c=(b.x*d-a.x*f+b.x-a.x)/c;d=(h*h+c*c)/4-1;if(d<0)return{x:0,y:0,ratio:-1};d=Math.sqrt(d);return{x:-h/2,y:-c/2,ratio:d>1E3?-1:d,a:h,b:c}}(a,b);h.a>1E3||h.b>1E3||h.ratio<0?(d.beginPath(),
d.moveTo(a.x*c,a.y*c),d.lineTo(b.x*c,b.y*c)):(b=Math.atan2(b.y-h.y,b.x-h.x),a=Math.atan2(a.y-h.y,a.x-h.x),f=f(b,a),d.beginPath(),d.arc(h.x*c,h.y*c,h.ratio*c,b,a,f));d.stroke()},contains:e.lambda(!1)}};n.Plot={initialize:function(a,b){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge;this.animation=new C;this.nodeTypes=new b.Plot.NodeTypes;this.edgeTypes=new b.Plot.EdgeTypes;this.labels=a.labels},nodeHelper:A,edgeHelper:E,Interpolator:{map:{border:"color",color:"color",
width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",fillStyle:"color",strokeStyle:"color",lineWidth:"number",shadowBlur:"number",shadowColor:"color",shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,b,c){return a+(b-a)*c},moebius:function(a,b,c,d){b=d.scale(-c);if(b.norm()<1){c=b.x;d=b.y;
var f=a.startPos.getc().moebiusTransformation(b);a.pos.setc(f.x,f.y);b.x=c;b.y=d}},linear:function(a,b,c){b=a.startPos.getc(!0);var d=a.endPos.getc(!0);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,d.y,c))},polar:function(a,b,c){b=a.startPos.getp(!0);c=a.endPos.getp().interpolate(b,c);a.pos.setp(c.theta,c.rho)},number:function(a,b,c,d,f){var h=a[d](b,"start");d=a[d](b,"end");a[f](b,this.compute(h,d,c))},color:function(a,b,c,d,f){var h=e.hexToRgb(a[d](b,"start"));d=e.hexToRgb(a[d](b,"end"));
var g=this.compute;c=e.rgbToHex([parseInt(g(h[0],d[0],c)),parseInt(g(h[1],d[1],c)),parseInt(g(h[2],d[2],c))]);a[f](b,c)},"array-number":function(a,b,c,d,f){var h=a[d](b,"start");d=a[d](b,"end");for(var g=[],e=0,i=h.length;e<i;e++){var k=h[e],l=d[e];if(k.length){for(var p=0,q=k.length,x=[];p<q;p++)x.push(this.compute(k[p],l[p],c));g.push(x)}else g.push(this.compute(k,l,c))}a[f](b,g)},node:function(a,b,c,d,f,h){d=this[d];if(b)for(var g=b.length,e=0;e<g;e++){var i=b[e];this[d[i]](a,i,c,f,h)}else for(i in d)this[d[i]](a,
i,c,f,h)},edge:function(a,b,c,d,f,h){a=a.adjacencies;for(var g in a)this.node(a[g],b,c,d,f,h)},"node-property":function(a,b,c){this.node(a,b,c,"map","getData","setData")},"edge-property":function(a,b,c){this.edge(a,b,c,"map","getData","setData")},"label-property":function(a,b,c){this.node(a,b,c,"label","getLabelData","setLabelData")},"node-style":function(a,b,c){this.node(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")},"edge-style":function(a,b,c){this.edge(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")}},
sequence:function(a){var b=this;a=e.merge({condition:e.lambda(!1),step:e.empty,onComplete:e.empty,duration:200},a||{});var c=setInterval(function(){a.condition()?a.step():(clearInterval(c),a.onComplete());b.viz.refresh(!0)},a.duration)},prepare:function(a){var b=this.viz.graph,c={"node-property":{getter:"getData",setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},
d={};if(e.type(a)=="array")for(var f=0,h=a.length;f<h;f++){var g=a[f].split(":");d[g.shift()]=g}else for(f in a)f=="position"?d[a.position]=[]:d[f]=e.splat(a[f]);b.eachNode(function(a){a.startPos.set(a.pos);e.each(["node-property","node-style"],function(b){if(b in d)for(var f=d[b],h=0,g=f.length;h<g;h++)a[c[b].setter](f[h],a[c[b].getter](f[h]),"start")});e.each(["edge-property","edge-style"],function(b){if(b in d){var f=d[b];a.eachAdjacency(function(a){for(var d=0,h=f.length;d<h;d++)a[c[b].setter](f[d],
a[c[b].getter](f[d]),"start")})}})});return d},animate:function(a,b){a=e.merge(this.viz.config,a||{});var c=this,d=this.viz.graph,f=this.Interpolator,h=a.type==="nodefx"?this.nodeFxAnimation:this.animation,g=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(!0);h.setOptions(e.merge(a,{$animating:!1,compute:function(h){d.eachNode(function(a){for(var c in g)f[c](a,g[c],h,b)});c.plot(a,this.$animating,h);this.$animating=!0},complete:function(){a.hideLabels&&c.labels.hideLabels(!1);c.plot(a);
a.onComplete();a.onAfterCompute()}})).start()},nodeFx:function(a){var b=this.viz,c=b.graph,d=this.nodeFxAnimation,f=e.merge(this.viz.config,{elements:{id:!1,properties:{}},reposition:!1});a=e.merge(f,a||{},{onBeforeCompute:e.empty,onAfterCompute:e.empty});d.stopTimer();var h=a.elements.properties;a.elements.id?(d=e.splat(a.elements.id),e.each(d,function(a){if(a=c.getNode(a))for(var b in h)a.setData(b,h[b],"end")})):c.eachNode(function(a){for(var b in h)a.setData(b,h[b],"end")});d=[];for(var g in h)d.push(g);
g=["node-property:"+d.join(":")];a.reposition&&(g.push("linear"),b.compute("end"));this.animate(e.merge(a,{modes:g,type:"nodefx"}))},plot:function(a,b){var c=this.viz,d=c.graph,f=c.canvas;c=c.root;var h=this,g=f.getCtx(),e=Math.min;a=a||this.viz.controller;a.clearCanvas&&f.clear();if(c=d.getNode(c)){var i=!!c.visited;d.eachNode(function(c){var d=c.getData("alpha");c.eachAdjacency(function(p){var q=p.nodeTo;if(!!q.visited===i&&c.drawn&&q.drawn)!b&&a.onBeforePlotLine(p),g.save(),g.globalAlpha=e(d,q.getData("alpha"),
p.getData("alpha")),h.plotLine(p,f,b),g.restore(),!b&&a.onAfterPlotLine(p)});g.save();c.drawn&&(!b&&a.onBeforePlotNode(c),h.plotNode(c,f,b),!b&&a.onAfterPlotNode(c));!h.labelsHidden&&a.withLabels&&(c.drawn&&d>=0.95?h.labels.plotLabel(f,c,a):h.labels.hideLabel(c,!1));g.restore();c.visited=!i})}},plotTree:function(a,b,c){var d=this,f=this.viz.canvas,h=f.getCtx(),g=a.getData("alpha");a.eachSubnode(function(e){if(b.plotSubtree(a,e)&&e.exist&&e.drawn){var i=a.getAdjacency(e.id);!c&&b.onBeforePlotLine(i);
h.globalAlpha=Math.min(g,e.getData("alpha"));d.plotLine(i,f,c);!c&&b.onAfterPlotLine(i);d.plotTree(e,b,c)}});a.drawn?(!c&&b.onBeforePlotNode(a),this.plotNode(a,f,c),!c&&b.onAfterPlotNode(a),!b.hideLabels&&b.withLabels&&g>=0.95?this.labels.plotLabel(f,a,b):this.labels.hideLabel(a,!1)):this.labels.hideLabel(a,!0)},plotNode:function(a,b,c){var d=a.getData("type"),f=this.node.CanvasStyles;if(d!="none"){var h=a.getData("lineWidth"),g=a.getData("color"),e=a.getData("alpha"),i=b.getCtx();i.lineWidth=h;i.fillStyle=
i.strokeStyle=g;i.globalAlpha=e;for(var k in f)i[k]=a.getCanvasStyle(k);this.nodeTypes[d].render.call(this,a,b,c)}},plotLine:function(a,b,c){var d=a.getData("type"),f=this.edge.CanvasStyles;if(d!="none"){var h=a.getData("lineWidth"),g=a.getData("color"),e=b.getCtx();e.lineWidth=h;e.fillStyle=e.strokeStyle=g;for(var i in f)e[i]=a.getCanvasStyle(i);this.edgeTypes[d].render.call(this,a,b,c)}}};n.Label={};n.Label.Native=new m({plotLabel:function(a,b,c){var d=a.getCtx();b.pos.getc(!0);d.font=b.getLabelData("style")+
" "+b.getLabelData("size")+"px "+b.getLabelData("family");d.textAlign=b.getLabelData("textAlign");d.fillStyle=d.strokeStyle=b.getLabelData("color");d.textBaseline=b.getLabelData("textBaseline");this.renderLabel(a,b,c)},renderLabel:function(a,b){var c=a.getCtx(),d=b.pos.getc(!0);c.fillText(b.name,d.x,d.y+b.getData("height")/2)},hideLabel:e.empty,hideLabels:e.empty});n.Label.DOM=new m({labelsHidden:!1,labelContainer:!1,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:
this.labelContainer=document.getElementById(this.viz.config.labelContainer)},getLabel:function(a){return a in this.labels&&this.labels[a]!=null?this.labels[a]:this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var b in this.labels)if(a||!this.viz.graph.hasNode(b))this.disposeLabel(b),delete this.labels[b]},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},
hideLabel:function(a,b){a=e.splat(a);var c=b?"":"none",d=this;e.each(a,function(a){if(a=d.getLabel(a.id))a.style.display=c})},fitsInCanvas:function(a,b){var c=b.getSize();if(a.x>=c.width||a.x<0||a.y>=c.height||a.y<0)return!1;return!0}});n.Label.HTML=new m({Implements:n.Label.DOM,plotLabel:function(a,b,c){a=b.id;var d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){d=document.createElement("div");var f=this.getLabelContainer();d.id=a;d.className="node";d.style.position="absolute";c.onCreateLabel(d,
b);f.appendChild(d);this.labels[b.id]=d}this.placeLabel(d,b,c)}});n.Label.SVG=new m({Implements:n.Label.DOM,plotLabel:function(a,b,c){a=b.id;var d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){d=document.createElementNS("http://www.w3.org/2000/svg","svg:text");var f=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");d.appendChild(f);f=this.getLabelContainer();d.setAttribute("id",a);d.setAttribute("class","node");f.appendChild(d);c.onCreateLabel(d,b);this.labels[b.id]=d}this.placeLabel(d,
b,c)}});n.Geom=new m({initialize:function(a){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge},translate:function(a,b){b=e.splat(b);this.viz.graph.eachNode(function(c){e.each(b,function(b){c.getPos(b).$add(a)})})},setRightLevelToShow:function(a,b,c){var d=this.getRightLevelToShow(a,b),f=this.viz.labels,h=e.merge({execShow:!0,execHide:!0,onHide:e.empty,onShow:e.empty},c||{});a.eachLevel(0,this.config.levelsToShow,function(b){if(b._depth-a._depth>d){if(h.onHide(b),h.execHide)b.drawn=
!1,b.exist=!1,f.hideLabel(b,!1)}else if(h.onShow(b),h.execShow)b.exist=!0});a.drawn=!0},getRightLevelToShow:function(a,b){var c=this.config,d=c.levelsToShow;if(!c.constrained)return d;for(;!this.treeFitsInCanvas(a,b,d)&&d>1;)d--;return d}});var H={construct:function(a){var b=e.type(a)=="array",c=new n(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);b?function(a,b){for(var c=function(c){for(var h=0,g=b.length;h<g;h++)if(b[h].id==c)return b[h];return a.addNode({id:c,name:c})},
g=0,j=b.length;g<j;g++){a.addNode(b[g]);var i=b[g].adjacencies;if(i)for(var k=0,l=i.length;k<l;k++){var p=i[k],q={};if(typeof i[k]!="string")q=e.merge(p.data,{}),p=p.nodeTo;a.addAdjacence(b[g],c(p),q)}}}(c,a):function(a,b){a.addNode(b);if(b.children)for(var c=0,g=b.children;c<g.length;c++)a.addAdjacence(b,g[c]),arguments.callee(a,g[c])}(c,a);return c},loadJSON:function(a,b){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(!0);this.graph=this.construct(a);this.root=e.type(a)!=
"array"?a.id:a[b?b:0].id},toJSON:function(a){if((a||"tree")=="tree"){var b={};b=function f(a){var b={};b.id=a.id;b.name=a.name;b.data=a.data;var c=[];a.eachSubnode(function(a){c.push(f(a))});b.children=c;return b}(this.graph.getNode(this.root))}else{b=[];var c=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(a){var h={};h.id=a.id;h.name=a.name;h.data=a.data;var g=[];a.eachAdjacency(function(a){var b=a.nodeTo;if(!!b.visited===c){var f={};f.nodeTo=b.id;f.data=a.data;g.push(f)}});
h.adjacencies=g;b.push(h);a.visited=!c})}return b}},F=$jit.Layouts={},I={label:null,compute:function(a,b,c){this.initializeLabel(c);var d=this.label,f=d.style;a.eachNode(function(a){var b=a.getData("autoWidth"),c=a.getData("autoHeight");if(b||c){delete a.data.$width;delete a.data.$height;delete a.data.$dim;var i=a.getData("width"),k=a.getData("height");f.width=b?"auto":i+"px";f.height=c?"auto":k+"px";d.innerHTML=a.name;b=d.offsetWidth;c=d.offsetHeight;i=a.getData("type");e.indexOf(["circle","square",
"triangle","star"],i)===-1?(a.setData("width",b),a.setData("height",c)):(b=b>c?b:c,a.setData("width",b),a.setData("height",b),a.setData("dim",b))}})},initializeLabel:function(a){if(!this.label)this.label=document.createElement("div"),document.body.appendChild(this.label);this.setLabelStyles(a)},setLabelStyles:function(){e.extend(this.label.style,{visibility:"hidden",position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}};F.Tree=function(){function a(a,b,c,d,
f){var h=b.Node,g=b.multitree;if(h.overridable){var e=-1,i=-1;a.eachNode(function(a){if(a._depth==c&&(!g||"$orn"in a.data&&a.data.$orn==d)){var b=a.getData("width",f);a=a.getData("height",f);e=e<b?b:e;i=i<a?a:i}});return{width:e<0?h.width:e,height:i<0?h.height:i}}else return h}function b(a,b,c,d){a.getPos(b)[d=="left"||d=="right"?"y":"x"]+=c}function c(a,b){var c=[];e.each(a,function(a){a=l.call(a);a[0]+=b;a[1]+=b;c.push(a)});return c}function d(a,b){if(a.length==0)return b;if(b.length==0)return a;
var c=a.shift(),f=b.shift();return[[c[0],f[1]]].concat(d(a,b))}function f(a,b){b=b||[];if(a.length==0)return b;var c=a.pop();return f(a,d(c,b))}function h(a,b,c,d,f){if(a.length<=f||b.length<=f)return 0;var e=a[f][1],g=b[f][0];return Math.max(h(a,b,c,d,++f)+c,e-g+d)}function g(a,b,f){function e(a,g,i){if(g.length<=i)return[];var j=g[i],k=h(a,j,b,f,0);return[k].concat(e(d(a,c(j,k)),g,++i))}return e([],a,0)}function j(a,b,f){function g(a,e,i){if(e.length<=i)return[];var j=e[i],k=-h(j,a,b,f,0);return[k].concat(g(d(c(j,
k),a),e,++i))}a=l.call(a);return g([],a.reverse(),0).reverse()}function i(a,b,c,d){var f=g(a,b,c);a=j(a,b,c);d=="left"?a=f:d=="right"&&(f=a);d=0;for(b=[];d<f.length;d++)b[d]=(f[d]+a[d])/2;return b}function k(d,h,e,g,j){function k(h,m,q){var n=h.getData(u,e),o=[],v=[],D=!1,C=(m||h.getData(t,e))+g.levelDistance;h.eachSubnode(function(b){if(b.exist&&(!l||"$orn"in b.data&&b.data.$orn==j))D||(D=a(d,g,b._depth,j,e)),b=k(b,D[t],q+C),o.push(b.tree),v.push(b.extent)});m=i(v,y,w,z);for(var B=0,A=[];B<o.length;B++)b(o[B],
e,m[B],j),A.push(c(v[B],m[B]));n=[[-n/2,n/2]].concat(f(A));h.getPos(e)[s]=0;j=="top"||j=="left"?h.getPos(e)[r]=q:h.getPos(e)[r]=-q;return{tree:h,extent:n}}var l=g.multitree,m=["x","y"],n=["width","height"],o=+(j=="left"||j=="right"),s=m[o],r=m[1-o],u=n[o],t=n[1-o],w=g.siblingOffset,y=g.subtreeOffset,z=g.align;k(h,!1,0)}var l=Array.prototype.slice;return new m({compute:function(a,b){var c=a||"start",d=this.graph.getNode(this.root);e.extend(d,{drawn:!0,exist:!0,selected:!0});I.compute(this.graph,c,
this.config);(b||!("_depth"in d))&&this.graph.computeLevels(this.root,0,"ignore");this.computePositions(d,c)},computePositions:function(a,b){var c=this.config,d=c.multitree,f=c.align,h=f!=="center"&&c.indent;c=c.orientation;var g=this;e.each(d?["top","right","bottom","left"]:[c],function(c){k(g.graph,a,b,g.config,c,b);var e=["x","y"][+(c=="left"||c=="right")];(function J(a){a.eachSubnode(function(g){if(g.exist&&(!d||"$orn"in g.data&&g.data.$orn==c))g.getPos(b)[e]+=a.getPos(b)[e],h&&(g.getPos(b)[e]+=
f=="left"?h:-h),J(g)})})(a)})}})}();$jit.ST=function(){function a(a){a=a||this.clickedNode;if(!this.config.constrained)return[];var b=this.geom,h=this.canvas,g=a._depth,e=[];this.graph.eachNode(function(b){b.exist&&!b.selected&&(b.isDescendantOf(a.id)?b._depth<=g&&e.push(b):e.push(b))});b=b.getRightLevelToShow(a,h);a.eachLevel(b,b,function(a){a.exist&&!a.selected&&e.push(a)});for(b=0;b<c.length;b++)h=this.graph.getNode(c[b]),h.isDescendantOf(a.id)||e.push(h);return e}function b(){var a=[],b=this.config;
this.clickedNode.eachLevel(0,b.levelsToShow,function(c){b.multitree&&!("$orn"in c.data)&&c.anySubnode(function(a){return a.exist&&!a.drawn})?a.push(c):c.drawn&&!c.anySubnode("drawn")&&a.push(c)});return a}var c=[];return new m({Implements:[H,t,F.Tree],initialize:function(a){var b=$jit.ST;a=this.controller=this.config=e.merge(r("Canvas","Fx","Tree","Node","Edge","Controller","Tips","NodeStyles","Events","Navigation","Label"),{levelsToShow:2,levelDistance:30,constrained:!0,Node:{type:"rectangle"},duration:700,
offsetX:0,offsetY:0},a);if(a.useCanvas)this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label";else{if(a.background)a.background=e.merge({type:"Circles"},a.background);this.canvas=new u(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:a.injectInto.id)+"-label"}this.graphOptions={complex:!0};this.graph=new n(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new b.Label[a.Label.type](this);this.fx=new b.Plot(this,b);this.op=new b.Op(this);
this.group=new b.Group(this);this.geom=new b.Geom(this);this.clickedNode=null;this.initializeExtras()},plot:function(){this.fx.plot(this.controller)},switchPosition:function(a,b,c){var e=this.geom,j=this.fx,i=this;if(!j.busy)j.busy=!0,this.contract({onComplete:function(){e.switchOrientation(a);i.compute("end",!1);j.busy=!1;if(b=="animate")i.onClick(i.clickedNode.id,c);else b=="replot"&&i.select(i.clickedNode.id,c)}},a)},switchAlignment:function(a,b,c){this.config.align=a;if(b=="animate")this.select(this.clickedNode.id,
c);else if(b=="replot")this.onClick(this.clickedNode.id,c)},addNodeInPath:function(a){c.push(a);this.select(this.clickedNode&&this.clickedNode.id||this.root)},clearNodesInPath:function(){c.length=0;this.select(this.clickedNode&&this.clickedNode.id||this.root)},refresh:function(){this.reposition();this.select(this.clickedNode&&this.clickedNode.id||this.root)},reposition:function(){this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(this.clickedNode,this.canvas);this.graph.eachNode(function(a){if(a.exist)a.drawn=
!0});this.compute("end")},requestNodes:function(a,b){var c=e.merge(this.controller,b),g=this.config.levelsToShow;if(c.request){var j=[],i=a._depth;a.eachLevel(0,g,function(a){if(a.drawn&&!a.anySubnode())j.push(a),a._level=g-(a._depth-i)});this.group.requestNodes(j,c)}else c.onComplete()},contract:function(b,c){var h=this.config.orientation,g=this.geom,j=this.group;c&&g.switchOrientation(c);var i=a.call(this);c&&g.switchOrientation(h);j.contract(i,e.merge(this.controller,b))},move:function(a,b){this.compute("end",
!1);var c=b.Move,g={x:c.offsetX,y:c.offsetY};c.enable&&this.geom.translate(a.endPos.add(g).$scale(-1),"end");this.fx.animate(e.merge(this.controller,{modes:["linear"]},b))},expand:function(a,c){this.group.expand(b.call(this,a),e.merge(this.controller,c))},selectPath:function(a){function b(a){if(!(a==null||a.selected))a.selected=!0,e.each(h.group.getSiblings([a])[a.id],function(a){a.exist=!0;a.drawn=!0}),a=a.getParents(),a=a.length>0?a[0]:null,b(a)}var h=this;this.graph.eachNode(function(a){a.selected=
!1});var g=0;for(a=[a.id].concat(c);g<a.length;g++)b(this.graph.getNode(a[g]))},setRoot:function(a,b,c){function e(){if(this.config.multitree&&l.data.$orn){var b={left:"right",right:"left",top:"bottom",bottom:"top"}[l.data.$orn];k.data.$orn=b;(function x(c){c.eachSubnode(function(c){if(c.id!=a)c.data.$orn=b,x(c)})})(k);delete l.data.$orn}this.root=a;this.clickedNode=l;this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(l,i,{execHide:!1,onShow:function(a){if(!a.drawn)a.drawn=
!0,a.setData("alpha",1,"end"),a.setData("alpha",0),a.pos.setc(l.pos.x,l.pos.y)}});this.compute("end");this.busy=!0;this.fx.animate({modes:["linear","node-property:alpha"],onComplete:function(){j.busy=!1;j.onClick(a,{onComplete:function(){c&&c.onComplete()}})}})}if(!this.busy){this.busy=!0;var j=this,i=this.canvas,k=this.graph.getNode(this.root),l=this.graph.getNode(a);delete k.data.$orns;b=="animate"?(e.call(this),j.selectPath(l)):b=="replot"&&(e.call(this),this.select(this.root))}},addSubtree:function(a,
b,c){b=="replot"?this.op.sum(a,e.extend({type:"replot"},c||{})):b=="animate"&&this.op.sum(a,e.extend({type:"fade:seq"},c||{}))},removeSubtree:function(a,b,c,g){var j=[];this.graph.getNode(a).eachLevel(+!b,!1,function(a){j.push(a.id)});c=="replot"?this.op.removeNode(j,e.extend({type:"replot"},g||{})):c=="animate"&&this.op.removeNode(j,e.extend({type:"fade:seq"},g||{}))},select:function(c,f){var h=this.group,g=this.geom,j=this.graph.getNode(c),i=this.canvas;this.graph.getNode(this.root);var k=e.merge(this.controller,
f),l=this;k.onBeforeCompute(j);this.selectPath(j);this.clickedNode=j;this.requestNodes(j,{onComplete:function(){h.hide(h.prepare(a.call(l)),k);g.setRightLevelToShow(j,i);l.compute("current");l.graph.eachNode(function(a){var b=a.pos.getc(!0);a.startPos.setc(b.x,b.y);a.endPos.setc(b.x,b.y);a.visited=!1});l.geom.translate(j.endPos.add({x:k.offsetX,y:k.offsetY}).$scale(-1),["start","current","end"]);h.show(b.call(l));l.plot();k.onAfterCompute(l.clickedNode);k.onComplete()}})},onClick:function(a,b){var c=
this.canvas,g=this,j=this.geom,i=this.config,k=e.merge(this.controller,{Move:{enable:!0,offsetX:i.offsetX||0,offsetY:i.offsetY||0},setRightLevelToShowConfig:!1,onBeforeRequest:e.empty,onBeforeContract:e.empty,onBeforeMove:e.empty,onBeforeExpand:e.empty},b);if(!this.busy){this.busy=!0;var l=this.graph.getNode(a);this.selectPath(l,this.clickedNode);this.clickedNode=l;k.onBeforeCompute(l);k.onBeforeRequest(l);this.requestNodes(l,{onComplete:function(){k.onBeforeContract(l);g.contract({onComplete:function(){j.setRightLevelToShow(l,
c,k.setRightLevelToShowConfig);k.onBeforeMove(l);g.move(l,{Move:k.Move,onComplete:function(){k.onBeforeExpand(l);g.expand(l,{onComplete:function(){g.busy=!1;k.onAfterCompute(a);k.onComplete()}})}})}})}})}}})}();$jit.ST.$extend=!0;$jit.ST.Op=new m({Implements:n.Op});$jit.ST.Group=new m({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.config=a.config;this.animation=new C;this.nodes=null},requestNodes:function(a,b){var c=0,d=a.length,f=this.viz;if(d==0)b.onComplete();for(var e=0;e<d;e++)b.request(a[e].id,
a[e]._level,{onComplete:function(a,e){if(e&&e.children)e.id=a,f.op.sum(e,{type:"nothing"});++c==d&&(f.graph.computeLevels(f.root,0),b.onComplete())}})},contract:function(a,b){var c=this;a=this.prepare(a);this.animation.setOptions(e.merge(b,{$animating:!1,compute:function(a){a==1&&(a=0.99);c.plotStep(1-a,b,this.$animating);this.$animating="contract"},complete:function(){c.hide(a,b)}})).start()},hide:function(a,b){for(var c=0;c<a.length;c++)a[c].eachLevel(1,!1,function(a){a.exist&&e.extend(a,{drawn:!1,
exist:!1})});b.onComplete()},expand:function(a,b){var c=this;this.show(a);this.animation.setOptions(e.merge(b,{$animating:!1,compute:function(a){c.plotStep(a,b,this.$animating);this.$animating="expand"},complete:function(){c.plotStep(void 0,b,!1);b.onComplete()}})).start()},show:function(a){var b=this.config;this.prepare(a);e.each(a,function(a){if(b.multitree&&!("$orn"in a.data)){delete a.data.$orns;var d=" ";a.eachSubnode(function(a){"$orn"in a.data&&d.indexOf(a.data.$orn)<0&&a.exist&&!a.drawn&&
(d+=a.data.$orn+" ")});a.data.$orns=d}a.eachLevel(0,b.levelsToShow,function(a){if(a.exist)a.drawn=!0})})},prepare:function(a){return this.nodes=this.getNodesWithChildren(a)},getNodesWithChildren:function(a){var b=[],c=this.config;a.sort(function(a,b){return(a._depth<=b._depth)-(a._depth>=b._depth)});for(var d=0;d<a.length;d++)if(a[d].anySubnode("exist")){for(var f=d+1,e=!1;!e&&f<a.length;f++)if(!c.multitree||"$orn"in a[f].data)e=e||a[d].isDescendantOf(a[f].id);e||b.push(a[d])}return b},plotStep:function(a,
b,c){var d=this.viz,f=this.config,h=d.canvas.getCtx(),g=this.nodes,j,i,k={};for(j=0;j<g.length;j++){i=g[j];k[i.id]=[];var l=f.multitree&&!("$orn"in i.data),m=l&&i.data.$orns;i.eachSubgraph(function(a){if(l&&m&&m.indexOf(a.data.$orn)>0&&a.drawn)a.drawn=!1,k[i.id].push(a);else if((!l||!m)&&a.drawn)a.drawn=!1,k[i.id].push(a)});i.drawn=!0}g.length>0&&d.fx.plot();for(j in k)e.each(k[j],function(a){a.drawn=!0});for(j=0;j<g.length;j++)i=g[j],h.save(),d.fx.plotSubtree(i,b,a,c),h.restore()},getSiblings:function(a){var b=
{};e.each(a,function(a){var d=a.getParents();if(d.length==0)b[a.id]=[a];else{var f=[];d[0].eachSubnode(function(a){f.push(a)});b[a.id]=f}});return b}});$jit.ST.Geom=new m({Implements:n.Geom,switchOrientation:function(a){this.config.orientation=a},dispatch:function(){var a=Array.prototype.slice.call(arguments),b=a.shift(),c=a.length,d=function(a){return typeof a=="function"?a():a};if(c==2)return b=="top"||b=="bottom"?d(a[0]):d(a[1]);else if(c==4)switch(b){case "top":return d(a[0]);case "right":return d(a[1]);
case "bottom":return d(a[2]);case "left":return d(a[3])}},getSize:function(a,b){var c=a.data,d=this.config,f=d.siblingOffset;c=d.multitree&&"$orn"in c&&c.$orn||d.orientation;d=a.getData("width")+f;f=a.getData("height")+f;return b?this.dispatch(c,d,f):this.dispatch(c,f,d)},getTreeBaseSize:function(a,b,c){var d=this.getSize(a,!0),f=0,e=this;if(c(b,a))return d;if(b===0)return 0;a.eachSubnode(function(a){f+=e.getTreeBaseSize(a,b-1,c)});return(d>f?d:f)+this.config.subtreeOffset},getEdge:function(a,b,c){var d=
function(b,c){return function(){return a.pos.add(new o(b,c))}},f=this.node,e=a.getData("width"),g=a.getData("height");if(b=="begin")if(f.align=="center")return this.dispatch(c,d(0,g/2),d(-e/2,0),d(0,-g/2),d(e/2,0));else if(f.align=="left")return this.dispatch(c,d(0,g),d(0,0),d(0,0),d(e,0));else if(f.align=="right")return this.dispatch(c,d(0,0),d(-e,0),d(0,-g),d(0,0));else throw"align: not implemented";else if(b=="end")if(f.align=="center")return this.dispatch(c,d(0,-g/2),d(e/2,0),d(0,g/2),d(-e/2,
0));else if(f.align=="left")return this.dispatch(c,d(0,0),d(e,0),d(0,g),d(0,0));else if(f.align=="right")return this.dispatch(c,d(0,-g),d(0,0),d(0,0),d(-e,0));else throw"align: not implemented";},getScaledTreePosition:function(a,b){var c=this.node,d=a.getData("width"),f=a.getData("height"),e=this.config.multitree&&"$orn"in a.data&&a.data.$orn||this.config.orientation,g=function(c,d){return function(){return a.pos.add(new o(c,d)).$scale(1-b)}};if(c.align=="left")return this.dispatch(e,g(0,f),g(0,0),
g(0,0),g(d,0));else if(c.align=="center")return this.dispatch(e,g(0,f/2),g(-d/2,0),g(0,-f/2),g(d/2,0));else if(c.align=="right")return this.dispatch(e,g(0,0),g(-d,0),g(0,-f),g(0,0));else throw"align: not implemented";},treeFitsInCanvas:function(a,b,c){b=b.getSize();b=this.dispatch(this.config.multitree&&"$orn"in a.data&&a.data.$orn||this.config.orientation,b.width,b.height);return this.getTreeBaseSize(a,c,function(a,b){return a===0||!b.anySubnode()})<b}});$jit.ST.Plot=new m({Implements:n.Plot,plotSubtree:function(a,
b,c,d){var f=this.viz,h=f.canvas,g=f.config;c=Math.min(Math.max(0.001,c),1);if(c>=0)a.drawn=!1,h=h.getCtx(),f=f.geom.getScaledTreePosition(a,c),h.translate(f.x,f.y),h.scale(c,c);this.plotTree(a,e.merge(b,{withLabels:!0,hideLabels:!!c,plotSubtree:function(){var b=g.multitree&&!("$orn"in a.data),c=b&&a.getData("orns");return!b||c.indexOf(elem.getData("orn"))>-1}}),d);if(c>=0)a.drawn=!0},getAlignedPos:function(a,b,c){var d=this.node;if(d.align=="center")a={x:a.x-b/2,y:a.y-c/2};else if(d.align=="left")d=
this.config.orientation,a=d=="bottom"||d=="top"?{x:a.x-b/2,y:a.y}:{x:a.x,y:a.y-c/2};else if(d.align=="right")d=this.config.orientation,a=d=="bottom"||d=="top"?{x:a.x-b/2,y:a.y-c}:{x:a.x-b,y:a.y-c/2};else throw"align: not implemented";return a},getOrientation:function(a){var b=this.config,c=b.orientation;if(b.multitree)b=a.nodeFrom,a=a.nodeTo,c="$orn"in b.data&&b.data.$orn||"$orn"in a.data&&a.data.$orn;return c}});$jit.ST.Label={};$jit.ST.Label.Native=new m({Implements:n.Label.Native,renderLabel:function(a,
b){var c=a.getCtx(),d=b.pos.getc(!0);c.fillText(b.name,d.x,d.y)}});$jit.ST.Label.DOM=new m({Implements:n.Label.DOM,placeLabel:function(a,b,c){var d=b.pos.getc(!0),f=this.viz.config,e=f.Node,g=this.viz.canvas,j=b.getData("width"),i=b.getData("height"),k=g.getSize(),l=d.x*g.scaleOffsetX+g.translateOffsetX;d=d.y*g.scaleOffsetY+g.translateOffsetY;if(e.align=="center")j={x:Math.round(l-j/2+k.width/2),y:Math.round(d-i/2+k.height/2)};else if(e.align=="left")f=f.orientation,j=f=="bottom"||f=="top"?{x:Math.round(l-
j/2+k.width/2),y:Math.round(d+k.height/2)}:{x:Math.round(l+k.width/2),y:Math.round(d-i/2+k.height/2)};else if(e.align=="right")f=f.orientation,j=f=="bottom"||f=="top"?{x:Math.round(l-j/2+k.width/2),y:Math.round(d-i+k.height/2)}:{x:Math.round(l-j+k.width/2),y:Math.round(d-i/2+k.height/2)};else throw"align: not implemented";i=a.style;i.left=j.x+"px";i.top=j.y+"px";i.display=this.fitsInCanvas(j,g)?"":"none";c.onPlaceLabel(a,b)}});$jit.ST.Label.SVG=new m({Implements:[$jit.ST.Label.DOM,n.Label.SVG],initialize:function(a){this.viz=
a}});$jit.ST.Label.HTML=new m({Implements:[$jit.ST.Label.DOM,n.Label.HTML],initialize:function(a){this.viz=a}});$jit.ST.Plot.NodeTypes=new m({none:{render:e.empty,contains:e.lambda(!1)},circle:{render:function(a,b){var c=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),c,c);c/=2;this.nodeHelper.circle.render("fill",{x:d.x+c,y:d.y+c},c,b)},contains:function(a){var b=a.getData("dim");a=this.getAlignedPos(a.pos.getc(!0),b,b);b/=2;this.nodeHelper.circle.contains({x:a.x+b,y:a.y+b},b)}},square:{render:function(a,
b){var c=a.getData("dim"),d=c/2;c=this.getAlignedPos(a.pos.getc(!0),c,c);this.nodeHelper.square.render("fill",{x:c.x+d,y:c.y+d},d,b)},contains:function(a){var b=a.getData("dim");a=this.getAlignedPos(a.pos.getc(!0),b,b);b/=2;this.nodeHelper.square.contains({x:a.x+b,y:a.y+b},b)}},ellipse:{render:function(a,b){var c=a.getData("width"),d=a.getData("height"),f=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.ellipse.render("fill",{x:f.x+c/2,y:f.y+d/2},c,d,b)},contains:function(a){var b=a.getData("width"),
c=a.getData("height");a=this.getAlignedPos(a.pos.getc(!0),b,c);this.nodeHelper.ellipse.contains({x:a.x+b/2,y:a.y+c/2},b,c,canvas)}},rectangle:{render:function(a,b){var c=a.getData("width"),d=a.getData("height"),f=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.rectangle.render("fill",{x:f.x+c/2,y:f.y+d/2},c,d,b)},contains:function(a){var b=a.getData("width"),c=a.getData("height");a=this.getAlignedPos(a.pos.getc(!0),b,c);this.nodeHelper.rectangle.contains({x:a.x+b/2,y:a.y+c/2},b,c,canvas)}}});
$jit.ST.Plot.EdgeTypes=new m({none:e.empty,line:{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,f=a.nodeTo,e=d._depth<f._depth,g=this.viz.geom.getEdge(e?d:f,"begin",c);c=this.viz.geom.getEdge(e?f:d,"end",c);this.edgeHelper.line.render(g,c,b)},contains:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,f=a.nodeTo,e=d._depth<f._depth,g=this.viz.geom.getEdge(e?d:f,"begin",c);c=this.viz.geom.getEdge(e?f:d,"end",c);return this.edgeHelper.line.contains(g,c,b,this.edge.epsilon)}},arrow:{render:function(a,
b){var c=this.getOrientation(a),d=a.nodeFrom,f=a.nodeTo,e=a.getData("dim"),g=this.viz.geom.getEdge(d,"begin",c);c=this.viz.geom.getEdge(f,"end",c);f=a.data.$direction;this.edgeHelper.arrow.render(g,c,e,f&&f.length>1&&f[0]!=d.id,b)},contains:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,f=a.nodeTo,e=d._depth<f._depth,g=this.viz.geom.getEdge(e?d:f,"begin",c);c=this.viz.geom.getEdge(e?f:d,"end",c);return this.edgeHelper.arrow.contains(g,c,b,this.edge.epsilon)}},"quadratic:begin":{render:function(a,
b){var c=this.getOrientation(a),d=a.nodeFrom,f=a.nodeTo,e=d._depth<f._depth,g=this.viz.geom.getEdge(e?d:f,"begin",c);d=this.viz.geom.getEdge(e?f:d,"end",c);f=a.getData("dim");e=b.getCtx();e.beginPath();e.moveTo(g.x,g.y);switch(c){case "left":e.quadraticCurveTo(g.x+f,g.y,d.x,d.y);break;case "right":e.quadraticCurveTo(g.x-f,g.y,d.x,d.y);break;case "top":e.quadraticCurveTo(g.x,g.y+f,d.x,d.y);break;case "bottom":e.quadraticCurveTo(g.x,g.y-f,d.x,d.y)}e.stroke()}},"quadratic:end":{render:function(a,b){var c=
this.getOrientation(a),d=a.nodeFrom,f=a.nodeTo,e=d._depth<f._depth,g=this.viz.geom.getEdge(e?d:f,"begin",c);d=this.viz.geom.getEdge(e?f:d,"end",c);f=a.getData("dim");e=b.getCtx();e.beginPath();e.moveTo(g.x,g.y);switch(c){case "left":e.quadraticCurveTo(d.x-f,d.y,d.x,d.y);break;case "right":e.quadraticCurveTo(d.x+f,d.y,d.x,d.y);break;case "top":e.quadraticCurveTo(d.x,d.y-f,d.x,d.y);break;case "bottom":e.quadraticCurveTo(d.x,d.y+f,d.x,d.y)}e.stroke()}},bezier:{render:function(a,b){var c=this.getOrientation(a),
d=a.nodeFrom,e=a.nodeTo,h=d._depth<e._depth,g=this.viz.geom.getEdge(h?d:e,"begin",c);d=this.viz.geom.getEdge(h?e:d,"end",c);e=a.getData("dim");h=b.getCtx();h.beginPath();h.moveTo(g.x,g.y);switch(c){case "left":h.bezierCurveTo(g.x+e,g.y,d.x-e,d.y,d.x,d.y);break;case "right":h.bezierCurveTo(g.x-e,g.y,d.x+e,d.y,d.x,d.y);break;case "top":h.bezierCurveTo(g.x,g.y+e,d.x,d.y-e,d.x,d.y);break;case "bottom":h.bezierCurveTo(g.x,g.y-e,d.x,d.y+e,d.x,d.y)}h.stroke()}}})})();
